# file params.yaml for DVC


prepare:
  categories:
    &a Grocery_and_Gourmet_Food
featurize:
  categories:
    *a
split_train_test:
  categories:
    *a
  split_ratio:
    0.7
generate_vectors:
  categories:
    *a
  d2v_params:
    dm:
      1
    vector_size:
      50
    min_count:
      1
    negative:
      5
    ns_exponent:
      0.5
    sample:
      0.00001
    workers:
      8
    epochs:
      10
