stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/interim
  featurize:
    cmd: python3 src/featurize.py
    deps:
    - data/interim
    - src/featurize.py
    outs:
    - data/processed
  split_train_test:
    cmd: python3 src/split_train_test.py
    deps:
    - data/processed
    - src/split_train_test.py
    outs:
    - data/evaluation
