# file params.yaml for DVC


prepare:
  categories:
    Grocery_and_Gourmet_Food
featurize:
  categories:
    Grocery_and_Gourmet_Food
split_train_test:
  categories:
    Grocery_and_Gourmet_Food
  split_ratio:
    0.7

